### ISSUE TITLE
House TV show not working

### ISSUE THREAD

**Issue by der-delios** [bbrown430/plex-poster-set-helper#15] opened 2024-04-02 22:30 UTC
Hey, thanks for the awesome application.

Sadly, trying to change the posters for the TV show House doesnt work.

Both PosterDB (https://theposterdb.com/set/24583) and mediux (https://mediux.pro/sets/17115) don't work. The applications seems to change season 1 episodes 1-6, but actually doesn't change anything. All other episodes or seasons can't be found.

**Comment by bbrown430** [comment] 2024-04-10 21:21
This is caused by there being more than one show with "House" in the title. If I parse for the year as well, that will be fixed. Will hopefully address this soon, thanks for bringing to my attention.

**Comment by bbrown430** [comment] 2024-04-13 16:54
@der-delios this should be fixed in the latest commit.

**Closed by bbrown430** 2024-04-13 16:54 UTC
